Add Stat Service
elGordoGato/explore-with-me pull request #1
Opened 2023-09-26 09:44 UTC by elGordoGato

### **Diploma: part I**
Added Stat Service API

2023-09-26 18:46 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-26 18:46 UTC, FanaticFiz commented on pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
Ты же понимаешь что зависимости в родительском `pom` будут у всех кто его наследует...
Т.е. например актуатор будет в dto

2023-09-26 18:46 UTC, FanaticFiz commented on ewm-stat-service/stat-server/src/main/resources/schema.sql
> +/*
Такого быть не должно

2023-09-26 18:46 UTC, FanaticFiz commented on ewm-stat-service/stat-server/pom.xml
> +    <modelVersion>4.0.0</modelVersion>
Нужно привести в порядок все `pom` файлы...
Проследи за структурой, чтобы все модули везде стояли на одинаковых местах.
Чтобы были пустые строки-разделители между properties, dependencies, build и другими секциями

2023-09-26 18:46 UTC, FanaticFiz commented on ewm-stat-service/stat-server/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
Вот эти свойства могли бы быть только в самом верхнем родителе

2023-09-27 07:48 UTC, elGordoGato commented on pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
Я просто фиг его знает что за актуатор, в тз без лишних объяснений сказали добавить его как зависимость в каждый сервис - я добавил ¯\_(ツ)_/¯

2023-09-27 17:37 UTC, FanaticFiz commented on pom.xml
> +            <artifactId>spring-boot-starter-actuator</artifactId>
Если в кратце и своими словами то это небольшой "проектик" который добавляет к веб сервису несколько эндпоинтов, по кторым можно спрашивать сервис о его состоянии, о его health статусе.

Тебе станут доступны несколько интерфейсов, реализовав которые ты сможешь, набросать свою реализацию, по которой потом будет проверятся жив ли этот сервис.

Эта штука очень удобна для того чтобы потом настроить докер контейнеры на проверку статуса живо ли приложение и соответствующий контейнер.

2023-09-27 17:38 UTC, FanaticFiz approved these changes

2023-09-27 17:38 UTC, FanaticFiz approved these changes

2023-09-28 15:36 UTC, merged